compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@octokit/plugin-retry@4.1.6':
    dependencies:
      '@octokit/request-error': 3.0.3

yarnPath: .yarn/releases/yarn-4.1.0.cjs
